### PR TITLE
use of localStorage instead of cookie

### LINKED ISSUE #18: Outliner causes browser to drop login cookie(s) on Explorer
Hi There,

I have outliner running on Angua based Intranet and am using outliner in the sidebar to fold the main navigation menu (so it's pretty important to the site)

I have found that in IE (and IE only), when the plugin is turned on, users are able to login, however when they click the first link or button in the wiki, the browser seems to drop the login cookie and the user is immediately logged out.  This has the effect of preventing the user from modifying or adding any content.

Deactivating outliner fixes the problem.

Selectively deactivating every other plugin on the site and testing each time does not fix the problem, so it's unlikely to be an interaction with another plugin.

Thanks

### PR DESCRIPTION
**Pull request by Vincent31Fr**
fix #18

### CODE REVIEW

**Review by michitux — CHANGES_REQUESTED** [review]
In general I think this is a great improvement. According to [the documentation](https://developer.mozilla.org/en-US/docs/Web/API/Storage/setItem), `setItem` can fail and we should catch errors. I think it would be okay to just ignore them or log them to the console (to be able to diagnose the problem when it happens) as most users won't get them and I assume that in most cases it is not such a big problem if the storage is not working.

**Comment by Vincent31Fr** [comment]
Yes you right, it's done in my last commit.
To be cleaner, I also changed the name of the conf variable.

**Comment by michitux** [comment]
I would have avoided checking access to the local storage on every page load using this separate function. Catching the exception should be enough.

@Vincent31Fr I've just granted you access to this repository so you can merge this change and whatever other changes you want directly. I'm not using this plugin (anymore? no idea where I have used this) and I don't have the time to maintain it. If you want to maintain it or officially adopt it, feel free. You can just keep contributing to this repository or change the download link to your fork, as you like it.

**Comment by Vincent31Fr** [comment]
Ok thanks!

If you don't use it, I can adopt it. I will update download link on dokuwiki plugin page . You should no longer receive notification at each update ;)

**Pull request closed without merging**
